before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/sacloud/go-template/version.Revision={{.ShortCommit}}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    binary: '{{ .ProjectName }}'
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Os }}-{{ .Arch }}'
changelog:
  skip: false
  filters:
    exclude:
      - '^docs:'

#---
# 以下は必要に応じて
#---

#checksum:
#  name_template: '{{ .ProjectName }}_SHA256SUMS'
#  algorithm: sha256

#signs:
#  - artifacts: checksum
#    args:
#      - "--local-user"
#      - "E37EC0B895A9AC27DC4919AB96CEB4B93D86849D"
#      - "--output"
#      - "${signature}"
#      - "--detach-sign"
#      - "${artifact}"
#      -

#release:
#  draft: true

#nfpms:
#  - homepage: https://docs.usacloud.jp/go-template
#    file_name_template: "{{ .ProjectName }}_{{ .Os }}-{{ .Arch }}"
#    maintainer: Usacloud <sacloud.users@gmail.com>
#    description: CLI to manage to resources on the SAKURA Cloud
#    license: Apache 2.0
#    formats:
#      - deb
#      - rpm

#brews:
#  - tap:
#      owner: sacloud
#      name: homebrew-go-template
#      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
#    url_template: "https://github.com/sacloud/go-template/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#    commit_author:
#      name: sacloud-bot
#      email: sacloud.users@gmail.com
#    homepage: "https://github.com/sacloud/go-template"
#    license: "Apache 2.0"
#    test: |
#      system "#{bin}/go-template --version"